# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17H5U8UKl4k-zyA4u9Ti7Gx0blB20lKtK
"""

a, b = [12,2]
if a > b:
  print("yes")

a ="textpython"
print(a[2:])

def func1():
  x = "5"
  print(x)
func1()

import random

print(random.randrange(1, 10))

txt = "The best things in life are free!"
print("free" in txt)

for x in "banana":
  print(x)

len(banana")

print("banana".upper())

strq =  "Hello, world, python"
print(strq.split(","))

p = ["a", "b", "c"]
p.append("c")
p

for x in range(len(p)):
  print(p[x])

i = 0
while i<len(p):
  print(p[i])
  i = i+1

"""[ list
( tuple
{ set
({ frozenset

//str
//int, float, complex
//list, tuple, range
//dict
//set, frozenset
//bool
//bytes, bytearray, memoryview
"""



fruits = ["apple", "banana", "cherry", "kiwi"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)
print(newlist)

newlist = [x for x in fruits if "a" in x]
newlist

thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

thislist.sort(reverse = True)

thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort()
print(thislist)

thislist.sort(key = str.lower)
print(thislist)

list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits

print(green, tropic, red)

thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i+1

for x in range(len(thistuple)):
  print(thistuple[x])