SELECT SUM(CITY.POPULATION) 
FROM COUNTRY 
INNER JOIN CITY ON COUNTRY.CODE = CITY.COUNTRYCODE 
WHERE COUNTRY.CONTINENT = 'asia'

SELECT CITY.NAME 
FROM COUNTRY 
INNER JOIN CITY ON COUNTRY.CODE = CITY.COUNTRYCODE
WHERE COUNTRY.CONTINENT = "AFRICA"