SELECT * FROM CITY WHERE POPULATION > 100000 AND COUNTRYCODE = "USA";

SELECT NAME FROM CITY WHERE POPULATION > 120000 AND CountryCode = "USA"

SELECT * FROM CITY 

SELECT * FROM CITY WHERE ID = 1661;

SELECT * FROM CITY WHERE COUNTRYCODE = "JPN"

SELECT NAME FROM CITY WHERE COUNTRYCODE = "JPN"

SELECT CITY, STATE FROM STATION

SELECT DISTINCT CITY FROM STATION WHERE MOD(ID, 2)= 0


SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION

SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC LIMIT 1;

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE "%A" 
OR CITY LIKE "%E"
OR CITY LIKE "%I" 
OR CITY LIKE "%O" 
OR CITY LIKE "%U"


SELECT DISTINCT CITY FROM STATION WHERE (CITY LIKE "A%" OR "E%" OR "I%" OR "O%" OR "U%") AND (CITY LIKE "%A" OR "%E" OR "%I" OR "%O" OR "%U" )

SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY SUBSTR(NAME, LENGTH(NAME)-2, 3), ID